# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/70743644-2b42-4d5b-a1f4-f67bab36d3bb";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  boot.initrd.luks.devices."root".device = "/dev/disk/by-uuid/eabccc76-eaf5-4a81-8a68-18ada6ae61b0";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9726-CF3C";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/ee78b2df-bfd4-4bdc-8f84-4778d4580a65";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  boot.initrd.luks.devices."home".device = "/dev/disk/by-uuid/e5216620-79a7-475a-8147-afb7007df6f0";

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/70743644-2b42-4d5b-a1f4-f67bab36d3bb";
      fsType = "btrfs";
      options = [ "subvol=@var" ];
    };

  fileSystems."/tmp" =
    { device = "/dev/disk/by-uuid/70743644-2b42-4d5b-a1f4-f67bab36d3bb";
      fsType = "btrfs";
      options = [ "subvol=@tmp" ];
    };

  fileSystems."/.snapshots" =
    { device = "/dev/disk/by-uuid/70743644-2b42-4d5b-a1f4-f67bab36d3bb";
      fsType = "btrfs";
      options = [ "subvol=@.snapshots" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
