# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];
  
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f7f0f34b-2586-4f96-a112-c072f13f82d1";
      fsType = "btrfs";
      options = [ "subvol=@" "noatime" "compress=zstd" ];
    };

  boot.initrd.luks.devices."ROOT".device = "/dev/disk/by-uuid/91875fbd-9b4b-4ed8-8ae1-cacbe9003c16";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1195-4533";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/f7f0f34b-2586-4f96-a112-c072f13f82d1";
      fsType = "btrfs";
      options = [ "subvol=@home" "noatime" "compress=zstd" ];
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/f7f0f34b-2586-4f96-a112-c072f13f82d1";
      fsType = "btrfs";
      options = [ "subvol=@var" "noatime" "compress=zstd" ];
    };

  fileSystems."/.snapshots" =
    { device = "/dev/disk/by-uuid/f7f0f34b-2586-4f96-a112-c072f13f82d1";
      fsType = "btrfs";
      options = [ "subvol=@.snapshots" "noatime" "compress=zstd" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/a85a6ce4-6da7-4ed0-988d-42daf953f0c0"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
